# =============================================================================
#  win-live-triage.ps1 — Advanced Windows Threat Hunting & Forensics
#  Usage: Run PowerShell as Administrator:
#         Set-ExecutionPolicy -Scope Process Bypass
#         .\win-live-triage.ps1
#  Output: win_live_triage_<timestamp>.txt   (raw log)
#          win_live_triage_<timestamp>.md     (human-readable report)
#          win_live_triage_iocs_<timestamp>.csv    (IOC pivot table)
# =============================================================================
#Requires -Version 5.0

$Timestamp   = Get-Date -Format "yyyyMMdd_HHmmss"
$ReportFile  = "win_live_triage_$Timestamp.txt"
$MdFile      = "win_live_triage_$Timestamp.md"
$CsvFile     = "win_live_triage_iocs_$Timestamp.csv"
$Alerts      = 0
$IOCs        = [System.Collections.Generic.List[PSObject]]::new()

# ─── Markdown accumulator ─────────────────────────────────────────────────────
$script:MdBuffer = [System.Text.StringBuilder]::new()

function Write-MD {
    param([string]$Line = "")
    [void]$script:MdBuffer.AppendLine($Line)
}
function Write-MD-Table-Row {
    param([string[]]$Cells)
    Write-MD ("| " + ($Cells -join " | ") + " |")
}
function Write-MD-Table-Header {
    param([string[]]$Headers)
    Write-MD-Table-Row $Headers
    Write-MD ("| " + (($Headers | ForEach-Object { "---" }) -join " | ") + " |")
}
function Flush-MD {
    $script:MdBuffer.ToString() | Out-File -FilePath $MdFile -Encoding UTF8
}
function Write-MD-Badge {
    param([string]$Severity)
    switch ($Severity) {
        'CRITICAL' { return "🔴 CRITICAL" }
        'HIGH'     { return "🟠 HIGH" }
        'MEDIUM'   { return "🟡 MEDIUM" }
        'LOW'      { return "🟢 LOW" }
        default    { return "⚪ INFO" }
    }
}

# ─── Colour / plain-text logging ─────────────────────────────────────────────
function Write-Log {
    param([string]$Text, [string]$Color = "White")
    Write-Host $Text -ForegroundColor $Color
    $Text | Out-File -FilePath $ReportFile -Append -Encoding UTF8
}
function Write-Sep { Write-Log ("─" * 76) "DarkCyan" }
function Write-Head {
    param([string]$Title, [string]$MdTitle = "")
    Write-Log ""; Write-Sep; Write-Log "  $Title" "Yellow"; Write-Sep; Write-Log ""
    Write-MD ""; Write-MD "---"; Write-MD ""
    Write-MD "## $(if ($MdTitle) { $MdTitle } else { $Title })"
    Write-MD ""
}
function Write-Alert {
    param([string]$Msg, [string]$Category = "GENERAL")
    Write-Log "  ⚠  ALERT [$Category]  $Msg" "Red"
    Write-MD "> ⚠️ **ALERT [$Category]** $Msg"
    Write-MD ""
    $script:Alerts++
}
function Add-IOC {
    param([string]$Type,[string]$Value,[string]$Context,[string]$Severity)
    $IOCs.Add([PSCustomObject]@{ Type=$Type; Value=$Value; Context=$Context; Severity=$Severity; Time=(Get-Date) })
}

# ─── Admin check ─────────────────────────────────────────────────────────────
$isAdmin = ([Security.Principal.WindowsPrincipal][Security.Principal.WindowsIdentity]::GetCurrent()
           ).IsInRole([Security.Principal.WindowsBuiltInRole]::Administrator)
if (-not $isAdmin) {
    Write-Log "  [!] NOT running as Administrator — many checks will be incomplete!" "Red"
    Write-Log "      Re-launch: Start-Process powershell -Verb RunAs" "Red"
    Write-Log ""
}

# ─── Markdown document header ────────────────────────────────────────────────
$os = Get-CimInstance Win32_OperatingSystem
$cs = Get-CimInstance Win32_ComputerSystem

Write-MD "# 🔍 Windows Live Triage & Threat Hunting Report"
Write-MD ""
Write-MD "> Generated by **win-live-triage.ps1**"
Write-MD ""
Write-MD "| Field | Value |"
Write-MD "| --- | --- |"
Write-MD "| **Generated** | $(Get-Date) |"
Write-MD "| **Hostname** | $env:COMPUTERNAME |"
Write-MD "| **OS** | $($os.Caption) Build $($os.BuildNumber) |"
Write-MD "| **Domain** | $env:USERDOMAIN |"
Write-MD "| **User** | $env:USERNAME |"
Write-MD "| **Admin Privileges** | $isAdmin |"
Write-MD "| **TXT Report** | $ReportFile |"
Write-MD "| **IOC CSV** | $CsvFile |"
Write-MD ""
if (-not $isAdmin) {
    Write-MD "> ⚠️ **WARNING:** Script was not run as Administrator. Many checks will be incomplete."
    Write-MD ""
}

# ─── Console banner ──────────────────────────────────────────────────────────
Write-Log ""
Write-Log "  ╔══════════════════════════════════════════════════════════════╗" "Green"
Write-Log "  ║     ADVANCED WINDOWS NETWORK & PROCESS FORENSICS TOOL       ║" "Green"
Write-Log "  ╚══════════════════════════════════════════════════════════════╝" "Green"
Write-Log ""
Write-Log "  Generated  : $(Get-Date)"
Write-Log "  Hostname   : $env:COMPUTERNAME"
Write-Log "  OS         : $($os.Caption) Build $($os.BuildNumber)"
Write-Log "  Domain     : $env:USERDOMAIN"
Write-Log "  User       : $env:USERNAME  (Admin: $isAdmin)"
Write-Log "  TXT Report : $ReportFile"
Write-Log "  MD Report  : $MdFile"
Write-Log "  IOC CSV    : $CsvFile"
Write-Log ""

# =============================================================================
Write-Head "SECTION 1 — SYSTEM IDENTITY & HARDWARE" "Section 1 — System Identity & Hardware"

$cpuName = (Get-CimInstance Win32_Processor | Select-Object -First 1).Name
Write-Log ("  Model : {0} {1}" -f $cs.Manufacturer, $cs.Model)
Write-Log ("  RAM   : {0} GB"  -f [math]::Round($cs.TotalPhysicalMemory/1GB,1))
Write-Log ("  CPU   : {0} x {1}" -f $cs.NumberOfProcessors, $cpuName)

Write-MD "### Hardware"
Write-MD ""
Write-MD "| Field | Value |"
Write-MD "| --- | --- |"
Write-MD "| **Model** | $($cs.Manufacturer) $($cs.Model) |"
Write-MD "| **RAM** | $([math]::Round($cs.TotalPhysicalMemory/1GB,1)) GB |"
Write-MD "| **CPU** | $($cs.NumberOfProcessors) x $cpuName |"
Write-MD ""

Write-Log ""; Write-Log "  Network Adapters:" "Cyan"
Write-MD "### Network Adapters"
Write-MD ""
Write-MD-Table-Header @("Interface","Name","MAC","IP")
Get-NetAdapter | Where-Object Status -eq Up | ForEach-Object {
    $ip = (Get-NetIPAddress -InterfaceIndex $_.InterfaceIndex -AddressFamily IPv4 -ErrorAction SilentlyContinue).IPAddress
    Write-Log ("  [{0}]  {1,-28} MAC:{2}  IP:{3}" -f $_.InterfaceDescription, $_.Name, $_.MacAddress, ($ip -join ","))
    Write-MD-Table-Row @($_.InterfaceDescription, $_.Name, $_.MacAddress, ($ip -join ","))
}
Write-MD ""

Write-Log ""; Write-Log "  DNS Servers:" "Cyan"
Write-MD "### DNS Configuration"
Write-MD ""
Write-MD-Table-Header @("Interface","DNS Servers")
Get-DnsClientServerAddress -AddressFamily IPv4 -ErrorAction SilentlyContinue |
    Where-Object ServerAddresses | ForEach-Object {
    Write-Log ("  {0,-25}  {1}" -f $_.InterfaceAlias, ($_.ServerAddresses -join ", "))
    Write-MD-Table-Row @($_.InterfaceAlias, ($_.ServerAddresses -join ", "))
}
Write-MD ""

$doh = Get-ItemProperty 'HKLM:\SYSTEM\CurrentControlSet\Services\Dnscache\Parameters' -ErrorAction SilentlyContinue
if ($doh.EnableAutoDoh -eq 2) {
    Write-Log "  DNS-over-HTTPS (DoH): ENABLED" "Yellow"
    Write-MD "> 🟡 DNS-over-HTTPS (DoH) is **enabled** — DNS queries may not be visible in plain captures."
    Write-MD ""
}

Write-Log ""; Write-Log "  Hosts file overrides:" "Cyan"
Write-MD "### Hosts File Overrides"
Write-MD ""
$hostsPath    = "$env:SystemRoot\System32\drivers\etc\hosts"
$hostsEntries = Get-Content $hostsPath -ErrorAction SilentlyContinue |
    Where-Object { $_ -notmatch '^\s*#' -and $_.Trim() -ne '' }
if ($hostsEntries) {
    Write-MD "```"
    $hostsEntries | ForEach-Object { Write-Log "  $_" "Yellow"; Write-MD $_ }
    Write-MD "```"
    Write-MD ""
    if ($hostsEntries.Count -gt 3) {
        Write-Alert "Hosts file has $($hostsEntries.Count) active entries — possible DNS hijack" "HOSTS-FILE"
        Add-IOC "HOSTS-FILE" $hostsPath "$($hostsEntries.Count) active overrides" "MEDIUM"
    }
} else {
    Write-Log "  (default/empty)" "DarkGray"
    Write-MD "_Default/empty — no overrides._"
    Write-MD ""
}

# =============================================================================
Write-Head "SECTION 2 — USER ACCOUNTS & PRIVILEGE AUDIT" "Section 2 — User Accounts & Privilege Audit"

Write-Log "  Local user accounts:" "Cyan"
Write-MD "### Local User Accounts"
Write-MD ""
Write-MD-Table-Header @("Username","Status","Last Logon","Notes")
Get-LocalUser | ForEach-Object {
    $lastLogon = if ($_.LastLogon) { $_.LastLogon.ToString("yyyy-MM-dd HH:mm") } else { "Never" }
    $status    = if ($_.Enabled) { "ENABLED" } else { "disabled" }
    $flag      = if ($_.Enabled -and $_.PasswordNeverExpires) { "⚠ PWD NEVER EXPIRES" } else { "" }
    Write-Log ("  {0,-25} {1,-8}  LastLogon:{2}  {3}" -f $_.Name, $status, $lastLogon, $flag)
    Write-MD-Table-Row @($_.Name, $status, $lastLogon, $flag)
    if ($_.Enabled -and $_.Name -notin @('Administrator','DefaultAccount','Guest','WDAGUtilityAccount') -and $_.PasswordNeverExpires) {
        Write-Alert "Account '$($_.Name)' enabled with non-expiring password" "USER-ACCOUNT"
        Add-IOC "USER-ACCOUNT" $_.Name "Password never expires" "MEDIUM"
    }
}
Write-MD ""

Write-Log ""; Write-Log "  Local Administrators:" "Cyan"
Write-MD "### Local Administrators"
Write-MD ""
Write-MD-Table-Header @("Name","Source")
try {
    Get-LocalGroupMember -Group "Administrators" -ErrorAction Stop | ForEach-Object {
        Write-Log ("  {0,-35} [{1}]" -f $_.Name, $_.PrincipalSource)
        Write-MD-Table-Row @($_.Name, $_.PrincipalSource)
    }
} catch { Write-Log "  (could not enumerate)" "DarkGray"; Write-MD "_Could not enumerate._" }
Write-MD ""

Write-Log ""; Write-Log "  Recent failed logins (Event 4625):" "Cyan"
Write-MD "### Failed Login Attempts"
Write-MD ""
Write-MD-Table-Header @("Username","Failures","Flag")
try {
    Get-WinEvent -FilterHashtable @{LogName='Security';Id=4625} -MaxEvents 50 -ErrorAction Stop |
        Group-Object { $_.Properties[5].Value } | Sort-Object Count -Descending |
        ForEach-Object {
            $f = if ($_.Count -ge 10) { "⚠️ POSSIBLE BRUTE FORCE" } else { "" }
            Write-Log ("  {0,-3} failures — {1}" -f $_.Count, $_.Name)
            Write-MD-Table-Row @($_.Name, $_.Count, $f)
            if ($_.Count -ge 10) {
                Write-Alert "Brute-force: $($_.Count) failed logins for '$($_.Name)'" "BRUTE-FORCE"
                Add-IOC "BRUTE-FORCE" $_.Name "$($_.Count) failed logins" "HIGH"
            }
        }
} catch { Write-Log "  (Security log not accessible)" "DarkGray"; Write-MD "_Security log not accessible._" }
Write-MD ""

Write-Log ""; Write-Log "  Privesc tool scan:" "Cyan"
Write-MD "### Privilege Escalation Tool Scan"
Write-MD ""
$privEscTools = @('mimikatz','meterpreter','cobalt','beacon','psexec','wce','fgdump','pwdump','gsecdump','lsadump','incognito')
$peFound = $false
Get-Process -ErrorAction SilentlyContinue | ForEach-Object {
    foreach ($t in $privEscTools) {
        if ($_.Name -like "*$t*") {
            Write-Alert "Privesc tool detected: $($_.Name) (PID:$($_.Id))" "CREDENTIAL-TOOL"
            Add-IOC "CREDENTIAL-TOOL" $_.Name "PID:$($_.Id)" "CRITICAL"
            $peFound = $true
        }
    }
}
if (-not $peFound) { Write-Log "  None detected." "DarkGray"; Write-MD "_None detected._" }
Write-MD ""

# =============================================================================
Write-Head "SECTION 3 — DETAILED PROCESS ANALYSIS" "Section 3 — Detailed Process Analysis"

Write-Log "  Enumerating processes with signatures..." "DarkGray"
Write-Log ""
Write-Log ("  {0,-6} {1,-6} {2,-24} {3,-10} {4,-12} {5}" -f "PID","PPID","NAME","CPU(s)","SIGNED","PATH")
Write-Log ("  {0,-6} {1,-6} {2,-24} {3,-10} {4,-12} {5}" -f "------","------","------------------------","----------","------------","----")

Write-MD "### All Running Processes"
Write-MD ""
Write-MD-Table-Header @("PID","PPID","Name","CPU(s)","Signed","Path")

$allProcs    = Get-CimInstance Win32_Process | Sort-Object KernelModeTime -Descending
$procDetails = @{}

foreach ($p in $allProcs) {
    $cpu    = [math]::Round(($p.KernelModeTime + $p.UserModeTime) / 1e7, 1)
    $path   = if ($p.ExecutablePath) { $p.ExecutablePath } else { "(system)" }
    $signed = "N/A"
    if ($p.ExecutablePath) {
        # Use LiteralPath to avoid casing/bracket issues on some driver paths
        $resolvedPath = try { (Get-Item -LiteralPath $p.ExecutablePath -EA Stop).FullName } catch { $p.ExecutablePath }
        if (Test-Path -LiteralPath $resolvedPath -EA SilentlyContinue) {
            try {
                $sigResult = Get-AuthenticodeSignature -LiteralPath $resolvedPath -EA Stop
                $signed = switch ($sigResult.Status) {
                    'Valid'                  { 'Valid' }
                    'NotSigned'              { 'NotSigned' }
                    'UnknownError'           { 'Unknown' }
                    'NotTrusted'             { 'NotTrusted' }
                    'HashMismatch'           { 'Tampered!' }
                    'NotSupportedFileFormat' { 'N/A' }
                    default                  { $sigResult.Status.ToString() }
                }
            } catch { $signed = "N/A" }
        }
    }
    $procDetails[$p.ProcessId] = @{ Name=$p.Name; Path=$path; Signed=$signed; PPID=$p.ParentProcessId }

    $color = "White"
    if ($signed -eq "NotSigned" -and $path -ne "(system)") { $color = "Yellow" }
    if ($path -match '\\Temp\\|\\AppData\\Local\\Temp|\\Downloads\\|\\Public\\') { $color = "Red" }

    Write-Log ("  {0,-6} {1,-6} {2,-24} {3,-10} {4,-12} {5}" -f
        $p.ProcessId, $p.ParentProcessId, $p.Name.Substring(0,[math]::Min(24,$p.Name.Length)),
        $cpu, $signed, $path) $color

    $sMd = switch ($signed) {
        "Valid"      { "✅ Valid" }
        "NotSigned"  { "⚠️ NotSigned" }
        "Tampered!"  { "🔴 Tampered!" }
        "NotTrusted" { "🔴 NotTrusted" }
        "N/A"        { "—" }
        default      { $signed }
    }
    Write-MD-Table-Row @($p.ProcessId, $p.ParentProcessId, $p.Name, $cpu, $sMd, $path)
}
Write-MD ""

Write-Log ""; Write-Log "  Unsigned executables outside system paths:" "Cyan"
Write-MD "### Unsigned Processes Outside System Paths"
Write-MD ""
$sysPaths     = @("$env:SystemRoot",'C:\Program Files','C:\Program Files (x86)')
$unsignedSusp = $allProcs | Where-Object {
    $ep = $_.ExecutablePath; if (-not $ep) { return $false }
    if ($sysPaths | Where-Object { $ep -like "$_*" }) { return $false }
    try { $rp = try { (Get-Item -LiteralPath $ep -EA Stop).FullName } catch { $ep }; (Get-AuthenticodeSignature -LiteralPath $rp -EA Stop).Status -ne 'Valid' } catch { $false }
}
if ($unsignedSusp) {
    Write-MD-Table-Header @("PID","Name","Path")
    $unsignedSusp | ForEach-Object {
        Write-Alert "Unsigned process: $($_.Name) [$($_.ExecutablePath)]" "UNSIGNED-PROC"
        Add-IOC "UNSIGNED-PROCESS" $_.ExecutablePath "PID:$($_.ProcessId)" "HIGH"
        Write-Log "     PID:$($_.ProcessId)  $($_.ExecutablePath)" "Red"
        Write-MD-Table-Row @($_.ProcessId, $_.Name, $_.ExecutablePath)
    }
} else { Write-Log "  None detected." "Green"; Write-MD "_None detected._" }
Write-MD ""

Write-Log ""; Write-Log "  Suspicious parent-child relationships:" "Cyan"
Write-MD "### Suspicious Parent-Child Relationships"
Write-MD ""
$suspParentChild = @(
    @{ Child='powershell.exe'; BadParents=@('winword.exe','excel.exe','outlook.exe','mspaint.exe','notepad.exe','explorer.exe','chrome.exe','msedge.exe','firefox.exe') }
    @{ Child='cmd.exe';        BadParents=@('winword.exe','excel.exe','outlook.exe','svchost.exe','lsass.exe') }
    @{ Child='wscript.exe';    BadParents=@('winword.exe','excel.exe','outlook.exe') }
    @{ Child='cscript.exe';    BadParents=@('winword.exe','excel.exe','outlook.exe') }
    @{ Child='mshta.exe';      BadParents=@('winword.exe','excel.exe','outlook.exe','explorer.exe') }
    @{ Child='regsvr32.exe';   BadParents=@('winword.exe','excel.exe','outlook.exe') }
    @{ Child='rundll32.exe';   BadParents=@('winword.exe','excel.exe','outlook.exe') }
)
$badRel = $false
foreach ($rule in $suspParentChild) {
    foreach ($cp in ($allProcs | Where-Object { $_.Name -ieq $rule.Child })) {
        if ($procDetails.ContainsKey($cp.ParentProcessId)) {
            $parentName = $procDetails[$cp.ParentProcessId].Name
            if ($parentName -iin $rule.BadParents) {
                Write-Alert "$($rule.Child) spawned by $parentName (PID:$($cp.ProcessId))" "PROCESS-INJECTION"
                Add-IOC "PROCESS-INJECTION" "$parentName→$($rule.Child)" "PID:$($cp.ProcessId)" "CRITICAL"
                $badRel = $true
            }
        }
    }
}
if (-not $badRel) { Write-Log "  None detected." "Green"; Write-MD "_None detected._" }
Write-MD ""

Write-Log ""; Write-Log "  DLLs loaded from suspicious paths:" "Cyan"
Write-MD "### DLL Hijack Check"
Write-MD ""
$suspDllPaths = @('\\Temp\\','\\tmp\\','\\AppData\\','\\Downloads\\','\\Public\\','\\Desktop\\')
$dllAlerts    = 0
Get-Process -EA SilentlyContinue | ForEach-Object {
    $proc = $_
    try {
        $proc.Modules | Where-Object { $m = $_.FileName; $suspDllPaths | Where-Object { $m -like "*$_*" } } |
        ForEach-Object {
            Write-Alert "Suspicious DLL: $($_.FileName) in $($proc.Name) (PID:$($proc.Id))" "DLL-HIJACK"
            Add-IOC "DLL-HIJACK" $_.FileName "In $($proc.Name) PID:$($proc.Id)" "HIGH"
            $dllAlerts++
        }
    } catch {}
}
if ($dllAlerts -eq 0) { Write-Log "  None detected." "Green"; Write-MD "_None detected._" }
Write-MD ""

# =============================================================================
Write-Head "SECTION 4 — NETWORK CONNECTIONS & IP INTELLIGENCE" "Section 4 — Network Connections & IP Intelligence"

# Build the richest possible PID → {Name, Owner} map:
#   1. Get-Process covers most user-space processes
#   2. Win32_Process via CIM covers kernel/system PIDs (4 = System, 0 = Idle, etc.)
#   3. Well-known PIDs are hardcoded as a fallback
$pidMap   = @{}
$ownerMap = @{}

# Well-known system PIDs
$pidMap[0]  = "Idle";    $ownerMap[0]  = "SYSTEM"
$pidMap[4]  = "System";  $ownerMap[4]  = "SYSTEM"

# Populate from Get-Process (fast, covers user processes)
Get-Process -EA SilentlyContinue | ForEach-Object { $pidMap[$_.Id] = $_.Name }

# Populate from WMI — fills in kernel PIDs Get-Process misses, and gives owner info
Get-CimInstance Win32_Process -EA SilentlyContinue | ForEach-Object {
    $pid_ = $_.ProcessId
    if (-not $pidMap.ContainsKey($pid_) -or $pidMap[$pid_] -eq "?") {
        $pidMap[$pid_] = if ($_.Name) { $_.Name } else { "PID:$pid_" }
    }
    try {
        $o = $_.GetOwner()
        $ownerMap[$pid_] = if ($o.User) { "$($o.Domain)\$($o.User)".TrimStart('') } else { "SYSTEM" }
    } catch {
        $ownerMap[$pid_] = "SYSTEM"
    }
}

function Resolve-PidName {
    param([int]$Pid_)
    if ($pidMap.ContainsKey($Pid_))   { return $pidMap[$Pid_] }
    # Last resort: query WMI directly for this one PID
    $w = Get-CimInstance Win32_Process -Filter "ProcessId=$Pid_" -EA SilentlyContinue
    if ($w) { $pidMap[$Pid_] = $w.Name; return $w.Name }
    return "PID:$Pid_"
}

function Resolve-PidOwner {
    param([int]$Pid_)
    if ($ownerMap.ContainsKey($Pid_)) { return $ownerMap[$Pid_] }
    try {
        $w = Get-CimInstance Win32_Process -Filter "ProcessId=$Pid_" -EA Stop
        $o = $w.GetOwner()
        $result = if ($o.User) { "$($o.Domain)\$($o.User)".TrimStart('\') } else { "SYSTEM" }
        $ownerMap[$Pid_] = $result
        return $result
    } catch { return "SYSTEM" }
}

$tcpConns = Get-NetTCPConnection -EA SilentlyContinue
$udpConns = Get-NetUDPEndpoint   -EA SilentlyContinue

Write-Log "  TCP Connections:" "Cyan"
Write-MD "### TCP Connections"
Write-MD ""
Write-MD-Table-Header @("PID","Process","State","Local","Remote","User")
foreach ($c in $tcpConns | Sort-Object State) {
    $pname  = Resolve-PidName  $c.OwningProcess
    $owner  = Resolve-PidOwner $c.OwningProcess
    $local  = "$($c.LocalAddress):$($c.LocalPort)"
    $remote = if ($c.RemoteAddress -and $c.RemoteAddress -ne '0.0.0.0' -and $c.RemotePort -ne 0) {
                  "$($c.RemoteAddress):$($c.RemotePort)"
              } else { "—" }
    Write-Log ("  {0,-6} {1,-22} {2,-12} {3,-26} {4,-26} {5}" -f $c.OwningProcess,
        $pname.Substring(0,[math]::Min(22,$pname.Length)), $c.State,
        $local.Substring(0,[math]::Min(26,$local.Length)),
        $remote.Substring(0,[math]::Min(26,$remote.Length)), $owner)
    Write-MD-Table-Row @($c.OwningProcess, $pname, $c.State, $local, $remote, $owner)
}
Write-MD ""

Write-Log ""; Write-Log "  UDP Endpoints:" "Cyan"
Write-MD "### UDP Endpoints"
Write-MD ""
Write-MD-Table-Header @("PID","Process","Address","Port","User")
$udpConns | Sort-Object LocalPort | ForEach-Object {
    $pname = Resolve-PidName $_.OwningProcess
    $owner = Resolve-PidOwner $_.OwningProcess
    Write-Log ("  {0,-6} {1,-22} {2,-22} {3,-6} {4}" -f $_.OwningProcess, $pname, $_.LocalAddress, $_.LocalPort, $owner)
    Write-MD-Table-Row @($_.OwningProcess, $pname, $_.LocalAddress, $_.LocalPort, $owner)
}
Write-MD ""

Write-Log ""; Write-Log "  External IP Resolution:" "Cyan"
Write-MD "### External IP Resolution & Threat Indicators"
Write-MD ""
$externalIPs = $tcpConns |
    Where-Object { $_.RemoteAddress -and $_.RemoteAddress -notmatch '^(0\.0\.0\.0|127\.|::)' -and $_.State -eq 'Established' } |
    Select-Object -ExpandProperty RemoteAddress -Unique |
    Where-Object { $_ -match '^\d+\.\d+\.\d+\.\d+$' }

# Only flag keywords strongly associated with malicious infrastructure
# Removed: host, vps, cloud, server, node, dedicated, dynamic, relay, coloc
# These are too common in legitimate ISP names (AWS, Azure, MEGA datacenters, etc.)
$suspKW = @('tor','onion','proxy','vpn','anon','bulletproof','no-log','offshore',
            'kp','by','ru-center','spamhaus','cyberbunker','choopa','vultr-')

if (-not $externalIPs) {
    Write-Log "  No external established connections." "DarkGray"
    Write-MD "_No external established IPv4 connections found._"
} else {
    Write-MD-Table-Header @("IP Address","Reverse DNS","Geo / ISP","Processes","Flag")
    foreach ($ip in $externalIPs) {
        $rdns = try { [System.Net.Dns]::GetHostEntry($ip).HostName } catch { "(unresolved)" }
        $geo  = "unknown"
        try {
            $g = Invoke-RestMethod -Uri "http://ip-api.com/json/$ip" -TimeoutSec 4 -EA Stop
            if ($g.status -eq 'success') { $geo = "$($g.countryCode) / $($g.isp)" }
        } catch {}
        $procs   = ($tcpConns | Where-Object { $_.RemoteAddress -eq $ip } |
            ForEach-Object { if ($pidMap.ContainsKey($_.OwningProcess)) { $pidMap[$_.OwningProcess] } else { "PID:$($_.OwningProcess)" } } |
            Sort-Object -Unique) -join ","
        $mdFlag  = "✅"
        $rdnsL   = $rdns.ToLower()
        foreach ($kw in $suspKW) {
            if ($rdnsL -like "*$kw*" -or $geo.ToLower() -like "*$kw*") {
                $mdFlag = "⚠️ SUSPICIOUS"
                Write-Alert "Suspicious remote: $ip → $rdns ($geo) via $procs" "SUSPICIOUS-IP"
                Add-IOC "SUSPICIOUS-IP" $ip "$rdns | $geo | $procs" "HIGH"
                break
            }
        }
        $color = if ($mdFlag -ne "✅") { "Red" } else { "White" }
        Write-Log ("  {0,-18} {1,-40} {2,-20} {3}" -f $ip, $rdns.Substring(0,[math]::Min(40,$rdns.Length)),
            $geo.Substring(0,[math]::Min(20,$geo.Length)), $procs) $color
        Write-MD-Table-Row @($ip, $rdns, $geo, $procs, $mdFlag)
    }
}
Write-MD ""

Write-Log ""; Write-Log "  ARP Table (duplicate MAC check):" "Cyan"
Write-MD "### ARP — Duplicate MAC Detection"
Write-MD ""
$arp    = Get-NetNeighbor -EA SilentlyContinue | Where-Object {
    $_.State -ne 'Unreachable' -and
    $_.LinkLayerAddress -ne '00-00-00-00-00-00' -and
    $_.LinkLayerAddress -ne '' -and
    # Exclude IPv4 multicast (01-00-5E-xx-xx-xx), IPv6 multicast (33-33-xx-xx-xx-xx), broadcast (FF-FF-FF-FF-FF-FF)
    $_.LinkLayerAddress -notmatch '^(01-00-5E|33-33|FF-FF-FF-FF-FF-FF)' -and
    # Exclude well-known multicast/broadcast IPs
    $_.IPAddress -notmatch '^(224\.|239\.|255\.255\.255\.255|ff0|ff02)' -and
    $_.IPAddress -notmatch '^ff'
}
$dupMAC = $arp | Group-Object LinkLayerAddress | Where-Object Count -gt 1
if ($dupMAC) {
    Write-MD-Table-Header @("MAC","Conflicting IPs")
    $dupMAC | ForEach-Object {
        Write-Alert "Duplicate MAC $($_.Name) — possible ARP poisoning!" "ARP-POISON"
        Add-IOC "ARP-POISON" $_.Name "Multiple IPs share MAC" "CRITICAL"
        $_.Group | ForEach-Object { Write-Log "    IP:$($_.IPAddress)  MAC:$($_.LinkLayerAddress)" "Red" }
        Write-MD-Table-Row @($_.Name, (($_.Group | Select-Object -ExpandProperty IPAddress) -join ", "))
    }
} else { Write-Log "  No duplicate MACs." "Green"; Write-MD "_No duplicate MACs detected._" }
Write-MD ""

Write-Log ""; Write-Log "  SYN_SENT flood check:" "Cyan"
Write-MD "### SYN_SENT Flood Check"
Write-MD ""
$synSent = $tcpConns | Where-Object State -eq 'SynSent'
if ($synSent.Count -gt 20) {
    Write-Alert "$($synSent.Count) SYN_SENT connections — possible scan/C2 beacon" "PORT-SCAN"
    Add-IOC "PORT-SCAN" "SYN_SENT x$($synSent.Count)" "Possible scanning" "HIGH"
} else {
    Write-Log "  SYN_SENT: $($synSent.Count) (normal)" "Green"
    Write-MD "_SYN\_SENT count: **$($synSent.Count)** — within normal range._"
}
Write-MD ""

# =============================================================================
Write-Head "SECTION 5 — PERSISTENCE MECHANISMS" "Section 5 — Persistence Mechanisms"

Write-Log "  [5.1] Registry autorun keys:" "Cyan"
Write-MD "### 5.1 Registry Autorun Keys"
Write-MD ""
$runKeys = @(
    'HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Run',
    'HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\RunOnce',
    'HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\RunServices',
    'HKCU:\SOFTWARE\Microsoft\Windows\CurrentVersion\Run',
    'HKCU:\SOFTWARE\Microsoft\Windows\CurrentVersion\RunOnce',
    'HKLM:\SOFTWARE\Wow6432Node\Microsoft\Windows\CurrentVersion\Run',
    'HKLM:\SYSTEM\CurrentControlSet\Services'
)
$regFound = $false
foreach ($key in $runKeys) {
    try {
        $entries = Get-ItemProperty -Path $key -EA Stop
        $entries.PSObject.Properties | Where-Object { $_.Name -notmatch '^PS' } | ForEach-Object {
            $val = $_.Value.ToString()
            Write-Log ("  {0}  →  {1}" -f $_.Name, $val)
            if (-not $regFound) { Write-MD-Table-Header @("Hive","Name","Value","Flag"); $regFound = $true }
            $rf = if ($val -match '\\AppData\\Local\\Temp|\\Downloads\\|Base64|IEX|Invoke-Expression|FromBase64') {
                Write-Alert "Suspicious autorun: $($_.Name) = $val" "REGISTRY-PERSIST"
                Add-IOC "REGISTRY-PERSIST" $_.Name $val "HIGH"
                "⚠️ SUSPICIOUS"
            } else { "" }
            Write-MD-Table-Row @($key.Split(':')[-1], $_.Name, $val, $rf)
        }
    } catch {}
}
if (-not $regFound) { Write-MD "_No autorun registry entries found._" }
Write-MD ""

Write-Log ""; Write-Log "  [5.2] Non-Microsoft scheduled tasks:" "Cyan"
Write-MD "### 5.2 Non-Microsoft Scheduled Tasks"
Write-MD ""
try {
    $tasks = Get-ScheduledTask -EA Stop | Where-Object { $_.TaskPath -notmatch '\\Microsoft\\' }
    if ($tasks) {
        Write-MD-Table-Header @("State","Task","Action","Flag")
        $tasks | ForEach-Object {
            $act = ($_.Actions | Select-Object -First 1).Execute
            $arg = ($_.Actions | Select-Object -First 1).Arguments
            Write-Log ("  [{0}] {1}`n        Action: {2} {3}" -f $_.State, ($_.TaskPath+$_.TaskName), $act, $arg)
            $tf = if ("$act $arg" -match 'powershell.*-enc|-w hidden|bypass|FromBase64|IEX|downloadstring|bitsadmin|certutil.*-decode|regsvr32.*scrobj') {
                Write-Alert "Suspicious task: $($_.TaskName)  →  $act $arg" "TASK-PERSIST"
                Add-IOC "SCHED-TASK" $_.TaskName "$act $arg" "HIGH"
                "⚠️ SUSPICIOUS"
            } else { "" }
            Write-MD-Table-Row @($_.State, ($_.TaskPath+$_.TaskName), "$act $arg", $tf)
        }
    } else { Write-Log "  None." "Green"; Write-MD "_None found._" }
} catch { Write-Log "  (Access denied)" "DarkGray"; Write-MD "_Access denied._" }
Write-MD ""

Write-Log ""; Write-Log "  [5.3] Non-standard running services:" "Cyan"
Write-MD "### 5.3 Non-Standard Running Services"
Write-MD ""
$knownPub = @('Microsoft','Windows','Intel','NVIDIA','AMD','Realtek','Broadcom','VMware','VirtualBox','Lenovo','Dell','HP')
$svcFound = $false
Get-Service -EA SilentlyContinue | Where-Object Status -eq Running | ForEach-Object {
    $svc = $_
    $ws  = Get-CimInstance Win32_Service -Filter "Name='$($svc.Name)'" -EA SilentlyContinue
    if ($ws -and -not ($knownPub | Where-Object { $ws.PathName -like "*$_*" -or $ws.Description -like "*$_*" }) -and $ws.PathName -notmatch 'System32|SysWOW64|Program Files') {
        Write-Log ("  {0,-35} {1}" -f $svc.Name, $ws.PathName) "Yellow"
        if (-not $svcFound) { Write-MD-Table-Header @("Service","Path","Flag"); $svcFound = $true }
        $sf = if ($ws.PathName -match '\\Temp\\|\\AppData\\|\\Downloads\\|\\Public\\') {
            Write-Alert "Service from suspicious path: $($svc.Name) → $($ws.PathName)" "SERVICE-PERSIST"
            Add-IOC "SERVICE-PERSIST" $svc.Name $ws.PathName "HIGH"; "⚠️ SUSPICIOUS PATH"
        } else { "" }
        Write-MD-Table-Row @($svc.Name, $ws.PathName, $sf)
    }
}
if (-not $svcFound) { Write-MD "_No non-standard services detected._" }
Write-MD ""

Write-Log ""; Write-Log "  [5.4] WMI Event Subscriptions:" "Cyan"
Write-MD "### 5.4 WMI Event Subscriptions"
Write-MD ""
try {
    $wmiF = Get-CimInstance -Namespace root\subscription -Class __EventFilter   -EA Stop
    $wmiC = Get-CimInstance -Namespace root\subscription -Class __EventConsumer -EA Stop
    $wmiB = Get-CimInstance -Namespace root\subscription -Class __FilterToConsumerBinding -EA Stop
    # Filter out the built-in SCM Event Log subscription that ships with Windows
    $realBindings = $wmiB | Where-Object { $_.Filter -notmatch 'SCM Event Log' }
    if ($realBindings) {
        Write-Alert "$($realBindings.Count) non-system WMI subscription(s) — possible fileless persistence!" "WMI-PERSIST"
        Write-MD-Table-Header @("Type","Name","Detail")
        $wmiF | Where-Object { $_.Name -ne 'SCM Event Log Filter' } | ForEach-Object { Write-Log "  Filter: $($_.Name)  $($_.Query)" "Red"; Write-MD-Table-Row @("Filter",$_.Name,$_.Query) }
        $wmiC | Where-Object { $_.Name -ne 'SCM Event Log Consumer' } | ForEach-Object { Write-Log "  Consumer: $($_.Name)" "Red"; Write-MD-Table-Row @("Consumer",$_.Name,"") }
        $realBindings | ForEach-Object { Add-IOC "WMI-PERSIST" $_.Filter.ToString() "WMI binding" "CRITICAL" }
    } else { Write-Log "  None detected (SCM Event Log subscription is built-in Windows, ignored)." "Green"; Write-MD "_None detected (built-in SCM subscription ignored)._" }
} catch { Write-Log "  (Access denied)" "DarkGray"; Write-MD "_Access denied to WMI namespace._" }
Write-MD ""

Write-Log ""; Write-Log "  [5.5] Browser extensions:" "Cyan"
Write-MD "### 5.5 Browser Extensions"
Write-MD ""
$extPaths = @(
    "$env:LOCALAPPDATA\Google\Chrome\User Data\Default\Extensions",
    "$env:LOCALAPPDATA\Microsoft\Edge\User Data\Default\Extensions"
)
$extFound = $false
foreach ($ep in $extPaths) {
    if (Test-Path $ep) {
        $br = if ($ep -like '*Chrome*') { 'Chrome' } else { 'Edge' }
        Get-ChildItem $ep -Directory -EA SilentlyContinue | ForEach-Object {
            $mf = Get-ChildItem $_.FullName -Recurse -Filter manifest.json -EA SilentlyContinue | Select-Object -First 1
            if ($mf) {
                try {
                    $m = Get-Content $mf.FullName -Raw | ConvertFrom-Json -EA Stop
                    $p = ($m.permissions -join ",")
                    # Resolve localised __MSG_xxx__ names via _locales/en/messages.json
                    $extName = $m.name
                    if ($extName -match '^__MSG_') {
                        $msgKey  = $extName -replace '^__MSG_|__$',''
                        $locFile = Join-Path (Split-Path $mf.FullName) "_locales\en\messages.json"
                        if (-not (Test-Path $locFile)) {
                            $locFile = Get-ChildItem (Split-Path $mf.FullName) "_locales\*\messages.json" -EA SilentlyContinue | Select-Object -First 1 -ExpandProperty FullName
                        }
                        if ($locFile -and (Test-Path $locFile)) {
                            try {
                                $msgs = Get-Content $locFile -Raw | ConvertFrom-Json -EA Stop
                                $resolved = $msgs.$msgKey.message
                                if ($resolved) { $extName = $resolved }
                            } catch {}
                        }
                        # If still unresolved, use the extension folder ID as fallback
                        if ($extName -match '^__MSG_') { $extName = "[ID: $($_.Name)] $extName" }
                    }
                    Write-Log ("  [{0}] {1,-40}  {2}" -f $br, $extName, $p.Substring(0,[math]::Min(60,$p.Length)))
                    if (-not $extFound) { Write-MD-Table-Header @("Browser","Extension","Permissions","Flag"); $extFound = $true }
                    $ef = if ($p -match 'nativeMessaging|debugger|proxy|<all_urls>|webRequest') {
                        Write-Alert "High-permission extension '$extName' [$br]" "BROWSER-EXTENSION"
                        Add-IOC "BROWSER-EXTENSION" $extName $p "MEDIUM"; "⚠️ HIGH PERMISSIONS"
                    } else { "" }
                    Write-MD-Table-Row @($br, $extName, $p.Substring(0,[math]::Min(80,$p.Length)), $ef)
                } catch {}
            }
        }
    }
}
if (-not $extFound) { Write-MD "_No extensions found or directories inaccessible._" }
Write-MD ""

# =============================================================================
Write-Head "SECTION 6 — FILE SYSTEM FORENSICS" "Section 6 — File System Forensics"

Write-Log "  [6.1] System EXEs modified last 72h:" "Cyan"
Write-MD "### 6.1 Recently Modified System Executables (72h)"
Write-MD ""
$recentExes = @("$env:SystemRoot\System32","$env:SystemRoot\SysWOW64","$env:SystemRoot\Temp") |
    ForEach-Object { Get-ChildItem $_ -Filter *.exe -EA SilentlyContinue | Where-Object { $_.LastWriteTime -gt (Get-Date).AddHours(-72) } }
if ($recentExes) {
    Write-MD-Table-Header @("File","Last Modified")
    $recentExes | ForEach-Object {
        Write-Alert "Recently modified: $($_.FullName)  $($_.LastWriteTime)" "FILE-TAMPER"
        Add-IOC "FILE-TAMPER" $_.FullName $_.LastWriteTime.ToString() "HIGH"
        Write-MD-Table-Row @($_.FullName, $_.LastWriteTime.ToString())
    }
} else { Write-Log "  None." "Green"; Write-MD "_None detected._" }
Write-MD ""

Write-Log ""; Write-Log "  [6.2] Alternate Data Streams:" "Cyan"
Write-MD "### 6.2 Alternate Data Streams (ADS)"
Write-MD ""
$adsN = 0
@("$env:TEMP","$env:USERPROFILE\Downloads") | ForEach-Object {
    if (Test-Path $_) {
        Get-ChildItem $_ -Recurse -EA SilentlyContinue | ForEach-Object {
            try {
                Get-Item $_.FullName -Stream * -EA Stop |
                    Where-Object { $_.Stream -ne ':$DATA' -and $_.Stream -ne 'Zone.Identifier' -and $_.Length -gt 0 } |
                    ForEach-Object {
                        Write-Alert "ADS: $($_.FileName)  Stream:$($_.Stream)  Size:$($_.Length)" "ADS-MALWARE"
                        Add-IOC "ADS" $_.FileName "Stream:$($_.Stream)" "HIGH"
                        if ($adsN -eq 0) { Write-MD-Table-Header @("File","Stream","Size (bytes)") }
                        Write-MD-Table-Row @($_.FileName, $_.Stream, $_.Length)
                        $adsN++
                    }
            } catch {}
        }
    }
}
if ($adsN -eq 0) { Write-Log "  None." "Green"; Write-MD "_None detected._" }
Write-MD ""

Write-Log ""; Write-Log "  [6.3] PowerShell history:" "Cyan"
Write-MD "### 6.3 PowerShell Command History (last 30 per user)"
Write-MD ""
$histFiles = Get-ChildItem "C:\Users\*\AppData\Roaming\Microsoft\Windows\PowerShell\PSReadLine\ConsoleHost_history.txt" -EA SilentlyContinue
if (-not $histFiles) { Write-MD "_No history files found._"; Write-MD "" }
foreach ($h in $histFiles) {
    $u = ($h.FullName -split '\\')[2]
    Write-Log "  --- $u ---" "Yellow"
    Write-MD "#### User: $u"
    Write-MD ""; Write-MD '```powershell'
    Get-Content $h.FullName -EA SilentlyContinue | Select-Object -Last 30 | ForEach-Object {
        Write-Log "  $_"
        Write-MD $_
        # Exclude the expected bypass command used to run this very script, and PS module manifests
        $isSelfBypass = ($_ -match 'Set-ExecutionPolicy.*-Scope Process.*Bypass')
        $isModuleManifest = ($_ -match '^\s*@\{\s*$|GUID\s*=|ModuleVersion\s*=')
        if (-not $isSelfBypass -and -not $isModuleManifest -and
            $_ -match 'IEX|Invoke-Expression|DownloadString|DownloadFile|-enc|-EncodedCommand|FromBase64|WebClient|Net\.WebRequest|bitsadmin|certutil.*decode|Start-Process.*hidden') {
            Write-Alert "Suspicious PS command: $_" "PS-HISTORY"
            Add-IOC "PS-HISTORY" $u $_ "HIGH"
        }
    }
    Write-MD '```'; Write-MD ""
}

Write-Log ""; Write-Log "  [6.4] Prefetch (last 20 executed):" "Cyan"
Write-MD "### 6.4 Prefetch — Recently Executed Programs"
Write-MD ""
if (Test-Path "$env:SystemRoot\Prefetch") {
    Write-MD-Table-Header @("Prefetch File","Last Run","Flag")
    Get-ChildItem "$env:SystemRoot\Prefetch" -Filter *.pf -EA SilentlyContinue |
        Sort-Object LastWriteTime -Descending | Select-Object -First 20 | ForEach-Object {
            Write-Log ("  {0,-45} {1}" -f $_.Name, $_.LastWriteTime)
            $pf = if ($_.Name -match 'MIMIKATZ|METERPRETER|PSEXEC|NETCAT|NC\.EXE|NMAP|COBALTSTRIKE|PWDUMP|WCES') {
                Write-Alert "Attack tool in prefetch: $($_.Name)" "TOOL-EXECUTION"
                Add-IOC "TOOL-EXECUTION" $_.Name $_.LastWriteTime.ToString() "CRITICAL"; "⚠️ KNOWN ATTACK TOOL"
            } else { "" }
            Write-MD-Table-Row @($_.Name, $_.LastWriteTime.ToString(), $pf)
        }
} else { Write-Log "  Not available." "DarkGray"; Write-MD "_Prefetch not available._" }
Write-MD ""

# =============================================================================
Write-Head "SECTION 7 — WINDOWS EVENT LOG ANALYSIS" "Section 7 — Windows Event Log Analysis"

Write-Log "  [7.1] Log tampering (1102/104):" "Cyan"
Write-MD "### 7.1 Audit Log Tampering"
Write-MD ""
$ltFound = $false
try {
    Get-WinEvent -FilterHashtable @{LogName='Security';Id=1102} -MaxEvents 10 -EA Stop | ForEach-Object {
        Write-Alert "Security log CLEARED at $($_.TimeCreated) by $($_.Properties[1].Value)" "LOG-TAMPER"
        Add-IOC "LOG-TAMPER" "Security Log Cleared" $_.TimeCreated.ToString() "CRITICAL"; $ltFound = $true
    }
} catch { Write-Log "  Security log: no clearing events." "Green" }
try {
    Get-WinEvent -FilterHashtable @{LogName='System';Id=104} -MaxEvents 10 -EA Stop | ForEach-Object {
        Write-Alert "System log CLEARED at $($_.TimeCreated)" "LOG-TAMPER"
        Add-IOC "LOG-TAMPER" "System Log Cleared" $_.TimeCreated.ToString() "CRITICAL"; $ltFound = $true
    }
} catch { Write-Log "  System log: no clearing events." "Green" }
if (-not $ltFound) { Write-MD "_No log-clearing events detected — good._" }
Write-MD ""

Write-Log ""; Write-Log "  [7.2] New services last 7 days (7045):" "Cyan"
Write-MD "### 7.2 Newly Installed Services (last 7 days)"
Write-MD ""
$nsFound = $false
try {
    Get-WinEvent -FilterHashtable @{LogName='System';Id=7045;StartTime=(Get-Date).AddDays(-7)} -EA Stop | ForEach-Object {
        if (-not $nsFound) { Write-MD-Table-Header @("Time","Service","Path"); $nsFound = $true }
        Write-Log ("  $($_.TimeCreated)  $($_.Properties[0].Value)  $($_.Properties[1].Value)") "Yellow"
        Write-MD-Table-Row @($_.TimeCreated.ToString(), $_.Properties[0].Value, $_.Properties[1].Value)
        Write-Alert "New service: $($_.Properties[0].Value)" "SERVICE-INSTALL"
        Add-IOC "SERVICE-INSTALL" $_.Properties[0].Value $_.Properties[1].Value "MEDIUM"
    }
} catch { Write-Log "  None / not accessible." "DarkGray" }
if (-not $nsFound) { Write-MD "_None in the past 7 days._" }
Write-MD ""

Write-Log ""; Write-Log "  [7.3] Suspicious PS script blocks (4104):" "Cyan"
Write-MD "### 7.3 Suspicious PowerShell Script Blocks"
Write-MD ""
$psFound = $false
try {
    Get-WinEvent -FilterHashtable @{LogName='Microsoft-Windows-PowerShell/Operational';Id=4104} -MaxEvents 200 -EA Stop |
        Where-Object { $_.Message -match 'IEX|Invoke-Expression|DownloadString|FromBase64|WebClient|hidden' } |
        Where-Object { $_.Message -notmatch 'GUID\s*=|ModuleVersion\s*=' } |
        Select-Object -First 10 | ForEach-Object {
            $snip = ($_.Message -split "`n")[0..2] -join " "
            Write-Log ("  $($_.TimeCreated)  $($snip.Substring(0,[math]::Min(120,$snip.Length)))") "Yellow"
            Write-Alert "Suspicious PS block at $($_.TimeCreated)" "PS-SCRIPTBLOCK"
            Add-IOC "PS-SCRIPTBLOCK" $_.TimeCreated.ToString() $snip "HIGH"
            if (-not $psFound) { Write-MD-Table-Header @("Time","Snippet"); $psFound = $true }
            Write-MD-Table-Row @($_.TimeCreated.ToString(), $snip.Substring(0,[math]::Min(100,$snip.Length)))
        }
} catch { Write-Log "  (Not enabled / access denied)" "DarkGray" }
if (-not $psFound) { Write-MD "_None found (or logging not enabled)._" }
Write-MD ""

Write-Log ""; Write-Log "  [7.4] Remote access logins last 7 days:" "Cyan"
Write-MD "### 7.4 Remote Access Logins (last 7 days)"
Write-MD ""
$raFound = $false
try {
    Get-WinEvent -FilterHashtable @{LogName='Security';Id=4624;StartTime=(Get-Date).AddDays(-7)} -MaxEvents 500 -EA Stop |
        Where-Object { $_.Properties[8].Value -in @(10,3) } | ForEach-Object {
            if (-not $raFound) { Write-MD-Table-Header @("Time","Domain","User","From IP","Type"); $raFound = $true }
            Write-Log ("  $($_.TimeCreated)  $($_.Properties[6].Value)\$($_.Properties[5].Value)  From:$($_.Properties[18].Value)")
            Write-MD-Table-Row @($_.TimeCreated.ToString(), $_.Properties[6].Value, $_.Properties[5].Value, $_.Properties[18].Value, $_.Properties[8].Value)
        }
} catch { Write-Log "  (Not accessible)" "DarkGray" }
if (-not $raFound) { Write-MD "_No remote logins in the past 7 days._" }
Write-MD ""

# =============================================================================
Write-Head "SECTION 8 — ANTI-FORENSICS DETECTION" "Section 8 — Anti-Forensics Detection"

Write-Log "  [8.1] Timestomping check:" "Cyan"
Write-MD "### 8.1 Timestomping Detection"
Write-MD ""
$tsFound = $false
Get-ChildItem $env:TEMP -EA SilentlyContinue | Where-Object { $_.CreationTime -gt $_.LastWriteTime.AddMinutes(5) } | ForEach-Object {
    Write-Alert "Timestomping: $($_.Name)  Created:$($_.CreationTime) > Modified:$($_.LastWriteTime)" "TIMESTOMP"
    Add-IOC "TIMESTOMP" $_.FullName "Created after modified" "MEDIUM"
    if (-not $tsFound) { Write-MD-Table-Header @("File","Created","Last Modified"); $tsFound = $true }
    Write-MD-Table-Row @($_.Name, $_.CreationTime.ToString(), $_.LastWriteTime.ToString())
}
if (-not $tsFound) { Write-Log "  None." "Green"; Write-MD "_None detected._" }
Write-MD ""

Write-Log ""; Write-Log "  [8.2] Volume Shadow Copies:" "Cyan"
Write-MD "### 8.2 Volume Shadow Copies"
Write-MD ""
try {
    $vss = Get-CimInstance Win32_ShadowCopy -EA Stop
    if ($vss) {
        Write-Log "  $($vss.Count) shadow copies found." "Green"
        Write-MD "> ✅ **$($vss.Count) shadow copy/copies present** — backup integrity intact."
        Write-MD ""
        Write-MD-Table-Header @("ID","Created","Volume")
        $vss | Select-Object -First 5 | ForEach-Object {
            Write-Log ("  ID:$($_.ID)  $($_.InstallDate)  $($_.VolumeName)")
            Write-MD-Table-Row @($_.ID, $_.InstallDate, $_.VolumeName)
        }
    } else {
        Write-Alert "No VSS copies — possible ransomware or VSS disabled!" "VSS-DELETED"
        Add-IOC "VSS-DELETED" "No shadow copies" "Ransomware indicator" "HIGH"
    }
} catch { Write-Log "  (Cannot query VSS)" "DarkGray"; Write-MD "_Cannot query VSS._" }
Write-MD ""

Write-Log ""; Write-Log "  [8.3] Attacker tool scan:" "Cyan"
Write-MD "### 8.3 Attacker Tool Scan"
Write-MD ""
$toolNames = @('mimikatz*','meterpreter*','nc.exe','ncat.exe','netcat*','psexec*','pwdump*',
               'wce.exe','fgdump*','gsecdump*','procdump*','cobalt*','beacon*','empire*',
               'metasploit*','nmap*','masscan*','sqlmap*','hydra*','hashcat*','john*')
$atFound = 0
foreach ($root in @($env:TEMP,"$env:USERPROFILE\Downloads","$env:USERPROFILE\Desktop","C:\Windows\Temp")) {
    foreach ($t in $toolNames) {
        Get-ChildItem -Path $root -Filter $t -EA SilentlyContinue | ForEach-Object {
            Write-Alert "Attack tool found: $($_.FullName)" "ATTACK-TOOL"
            Add-IOC "ATTACK-TOOL" $_.FullName $_.LastWriteTime.ToString() "CRITICAL"
            if ($atFound -eq 0) { Write-MD-Table-Header @("File","Last Modified") }
            Write-MD-Table-Row @($_.FullName, $_.LastWriteTime.ToString())
            $atFound++
        }
    }
}
if ($atFound -eq 0) { Write-Log "  None." "Green"; Write-MD "_None found._" }
Write-MD ""

# =============================================================================
Write-Head "SECTION 9 — SOFTWARE & PATCH STATUS" "Section 9 — Software & Patch Status"

Write-Log "  [9.1] Installed software:" "Cyan"
Write-MD "### 9.1 Installed Software"
Write-MD ""
Write-MD-Table-Header @("Name","Version","Publisher","Install Date")
Get-ItemProperty 'HKLM:\Software\Microsoft\Windows\CurrentVersion\Uninstall\*',
                 'HKCU:\Software\Microsoft\Windows\CurrentVersion\Uninstall\*' -EA SilentlyContinue |
    Where-Object DisplayName | Sort-Object DisplayName |
    ForEach-Object {
        Write-Log ("  {0,-45} v{1,-12} {2}" -f $_.DisplayName, $_.DisplayVersion, $_.Publisher)
        Write-MD-Table-Row @($_.DisplayName, $_.DisplayVersion, $_.Publisher, $_.InstallDate)
    }
Write-MD ""

Write-Log ""; Write-Log "  [9.2] Windows Update history (last 10):" "Cyan"
Write-MD "### 9.2 Windows Update History"
Write-MD ""
try {
    $ses = New-Object -ComObject Microsoft.Update.Session
    $sch = $ses.CreateUpdateSearcher()
    $cnt = $sch.GetTotalHistoryCount()
    if ($cnt -gt 0) {
        Write-MD-Table-Header @("Result","Title","Date")
        $sch.QueryHistory(0,[math]::Min(10,$cnt)) | ForEach-Object {
            $r = switch ($_.ResultCode) {1{"Incomplete"} 2{"Succeeded"} 3{"SucceededWithErrors"} 4{"Failed"} 5{"Aborted"} default{"Unknown"}}
            Write-Log ("  [$r] $($_.Title.Substring(0,[math]::Min(60,$_.Title.Length)))  $($_.Date)")
            Write-MD-Table-Row @($r, $_.Title.Substring(0,[math]::Min(80,$_.Title.Length)), $_.Date.ToString())
        }
    }
} catch { Write-Log "  (Not accessible)" "DarkGray"; Write-MD "_Not accessible._" }
Write-MD ""

# =============================================================================
Write-Head "SECTION 10 — IOC SUMMARY & THREAT SCORE" "Section 10 — IOC Summary & Threat Score"

$critical = ($IOCs | Where-Object Severity -eq 'CRITICAL').Count
$high     = ($IOCs | Where-Object Severity -eq 'HIGH').Count
$medium   = ($IOCs | Where-Object Severity -eq 'MEDIUM').Count
$score    = ($critical * 10) + ($high * 5) + ($medium * 2)
$scoreCap = [math]::Min($score, 100)

Write-Log ("  Alerts        : {0}" -f $Alerts)
Write-Log ("  CRITICAL IOCs : {0}" -f $critical) $(if ($critical -gt 0) {"Red"} else {"Green"})
Write-Log ("  HIGH IOCs     : {0}" -f $high)     $(if ($high -gt 0)     {"Red"} else {"Green"})
Write-Log ("  MEDIUM IOCs   : {0}" -f $medium)   $(if ($medium -gt 0)   {"Yellow"} else {"Green"})
Write-Log ("  Threat Score  : {0}/100" -f $scoreCap)

$rating = switch ($score) {
    { $_ -eq 0  } { "CLEAN — No indicators found" }
    { $_ -le 10 } { "LOW RISK — Minor anomalies, likely benign" }
    { $_ -le 30 } { "MEDIUM RISK — Investigate flagged items" }
    { $_ -le 60 } { "HIGH RISK — Strong indicators of compromise" }
    default        { "CRITICAL — Active threat likely present" }
}
$rColor = if ($score -gt 30) {"Red"} elseif ($score -gt 0) {"Yellow"} else {"Green"}
Write-Log ""; Write-Log "  VERDICT: $rating" $rColor; Write-Log ""

$badge = if ($score -eq 0) {"🟢"} elseif ($score -le 10) {"🟡"} elseif ($score -le 30) {"🟠"} else {"🔴"}
Write-MD "### Threat Scorecard"
Write-MD ""
Write-MD "| Metric | Count |"
Write-MD "| --- | --- |"
Write-MD "| 🔴 CRITICAL IOCs | $critical |"
Write-MD "| 🟠 HIGH IOCs | $high |"
Write-MD "| 🟡 MEDIUM IOCs | $medium |"
Write-MD "| ⚠️ Total Alerts | $Alerts |"
Write-MD "| **Threat Score** | **$scoreCap / 100** |"
Write-MD ""
Write-MD "### $badge Verdict: $rating"
Write-MD ""

if ($IOCs.Count -gt 0) {
    Write-Log "  IOC List:" "Cyan"
    Write-MD "### Full IOC List"
    Write-MD ""
    Write-MD-Table-Header @("Severity","Type","Value","Context","Time")
    $IOCs | ForEach-Object {
        Write-Log ("  [{0,-8}] {1,-20} {2,-38} {3}" -f $_.Severity, $_.Type,
            $_.Value.Substring(0,[math]::Min(38,$_.Value.Length)),
            $_.Context.Substring(0,[math]::Min(50,$_.Context.Length)))
        Write-MD-Table-Row @((Write-MD-Badge $_.Severity), $_.Type, $_.Value, $_.Context, $_.Time.ToString("yyyy-MM-dd HH:mm"))
    }
    Write-MD ""
    $IOCs | Export-Csv -Path $CsvFile -NoTypeInformation -Encoding UTF8
    Write-Log "  IOCs → $CsvFile" "Cyan"
    Write-MD "> 📄 IOCs exported to ``$CsvFile``"
    Write-MD ""
}

Write-MD "---"
Write-MD ""
Write-MD "_Cross-reference suspicious IPs: [VirusTotal](https://www.virustotal.com) · [AbuseIPDB](https://www.abuseipdb.com)_"
Write-MD ""
Write-MD "_Generated by network\_forensics\_deep.ps1_"

Write-Sep
Write-Log "  TXT  : $((Resolve-Path $ReportFile -EA SilentlyContinue).Path ?? $ReportFile)" "Cyan"
Write-Log "  MD   : $((Resolve-Path $MdFile     -EA SilentlyContinue).Path ?? $MdFile)" "Cyan"
Write-Log "  Note : Cross-reference IPs at virustotal.com / abuseipdb.com" "DarkGray"
Write-Sep
Write-Log ""

Flush-MD
Write-Host "  ✅ Markdown report written: $MdFile" -ForegroundColor Green